# create a travis env variable to get the first 6 chars of the git commit hash. $TRAVIS_COMMIT has the full hash value.
sudo: required
services:
  - docker
before_install:
  - ./bin/config-build-container.sh
script:
  - ./bin/test-proj.sh
  - docker build -t homeless-service .
after_success:
  - ./bin/push.sh
